name: publish

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      # - name: Lint
      #   run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Login
        run: |
          pnpm login --auth-type=legacy <<EOF 
          1cedsoda
          ${{ secrets.NPM_TOKEN }}
          EOF

      - name: Publish
        run: pnpm run publish
